"use client";
import { Board } from "./types";

const board = [
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
  [
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
    {
      ship: false,
      details: {
        id: "noship",
        burst: false,
        start: false,
        end: false,
        vertical: false,
      },
      validHover: null,
    },
  ],
];

export function initialBoardConfig() {
  const copyArray: Board[][] = board.map(function (arr) {
    return arr.slice();
  });
  return copyArray;
}
